services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./vendor:/app/vendor:cached
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}