version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=${APP_ENV:-production}
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-mydatabase}
      - DB_USER=${DB_USER:-dbuser}
      - DB_PASS=${DB_PASS:-dbpassword}