version: '3.8'

services:
  # PHP application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - app_network
    depends_on:
      - mysql
    command: php cmd.php serve
    environment:
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-app_db}
      - DB_USERNAME=${DB_USERNAME:-app_user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}

  # Nginx service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"  # For SSL support
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl  # For SSL certificates
    networks:
      - app_network
    depends_on:
      - app

  # MySQL service
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app_db}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-app_user}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

# Persistent volumes
volumes:
  mysql_data:
    driver: local

# Docker networks
networks:
  app_network:
    driver: bridge